[book]
authors = ["Ingolf Wagner"]
language = "en"
multilingual = false
src = "src"
title = "terranix"


[output.html]
default-theme = "terranix"
no-section-label = true
additional-js = ["theme/nix.min.js"]
git-repository-url = "https://github.com/terranix/terranix"
git-repository-icon = "fa-github"

[output.html.print]
enable = false

[output.linkcheck]
# Should we check links on the internet? Enabling this option adds a
# non-negligible performance impact
follow-web-links = false
